# Generated by Django 4.2.30 on 2026-06-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='offer',
            name='applies_to',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('THEATER', 'Theater Booking')], default='DINE_IN', help_text='Whether this offer applies to dine-in orders or theater bookings.', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='coupon_code',
            field=models.CharField(help_text='Coupon code user enters at checkout.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Percentage discount (1-100).'),
            preserve_default=False,
        ),
    ]
