# Generated by Django 5.2.15 on 2026-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_booking_payment_payment_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Advance'), ('REMAINING', 'Remaining'), ('FULL', 'Full'), ('REFUND', 'Refund')], max_length=15),
        ),
    ]
