# Generated by Django 5.0.14 on 2026-07-11 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_celebrationbooking'),
        ('payments', '0003_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='celebration_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.celebrationbooking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('ORDER', 'Order'), ('CELEBRATION', 'Celebration')], max_length=15),
        ),
    ]
