# Generated by Django 5.2.15 on 2026-06-15 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_request',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Half of the total amount – paid up‑front.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current lifecycle status.', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='movie_name',
            field=models.CharField(default='Legacy Booking', help_text='Title of the movie to be shown.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of guests (1‑8).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], default='PARTIAL', help_text='Current payment state.', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='screen_name',
            field=models.CharField(default='Screen 1', editable=False, help_text='Name of the screen – always "Screen 1".', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Optional free‑form request from the customer.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('10:00-13:00', '10:00 AM – 01:00 PM'), ('14:00-17:00', '02:00 PM – 05:00 PM'), ('18:00-21:00', '06:00 PM – 09:00 PM')], default='18:00-21:00', help_text='One of the three permitted time slots.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculated total price (₹250 per guest).', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Date on which the theater is reserved.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the booking was created.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier for the booking.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last update.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='User who created the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
