# Generated by Django 4.2.30 on 2026-06-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('10:00-13:00', '10:00 AM – 01:00 PM'), ('14:00-17:00', '02:00 PM – 05:00 PM'), ('18:00-21:00', '06:00 PM – 09:00 PM'), ('21:00-00:00', 'Night (9:00 PM - 12:00 AM)')], help_text='One of the three permitted time slots.', max_length=20),
        ),
    ]
