# Generated by Django 5.2.15 on 2026-06-16 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the notification.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short title of the notification.', max_length=255)),
                ('message', models.TextField(help_text='Full message body of the notification.')),
                ('notification_type', models.CharField(choices=[('BOOKING', 'Booking'), ('ORDER', 'Order'), ('OFFER', 'Offer')], help_text='Category of the notification.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', help_text='Delivery status of the notification.', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read the notification.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the notification was last updated.')),
                ('user', models.ForeignKey(help_text='Recipient of the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx')],
            },
        ),
    ]
